-- =============================================================
-- Study Buddy — SQLite Schema (Development / Self-Hosted)
-- Compatible: SQLite 3.35+
--
-- Key differences from schema.pg.sql:
--   • UUID PKs use TEXT (no native UUID type); generated by app layer
--   • JSONB → TEXT (stored as JSON strings, parsed by app)
--   • INT[] arrays → TEXT (JSON-encoded arrays e.g. '[0,1,3]')
--   • TIMESTAMPTZ → TEXT (ISO-8601 strings)
--   • BIGSERIAL → INTEGER PRIMARY KEY AUTOINCREMENT
--   • NUMERIC(p,s) → REAL
--   • No partial indexes (WHERE clause not supported in all contexts)
--   • updated_at triggers use SQLite trigger syntax
--   • No views that reference filtered indexes
--   • FOREIGN KEY enforcement: run 'PRAGMA foreign_keys = ON;' per connection
-- =============================================================

PRAGMA journal_mode = WAL;       -- better concurrency
PRAGMA foreign_keys = ON;        -- enforce FK constraints
PRAGMA synchronous = NORMAL;     -- safe + faster than FULL for WAL


-- =============================================================
-- 1. USERS
-- =============================================================

CREATE TABLE IF NOT EXISTS users (
    id              TEXT    PRIMARY KEY,                -- UUID (app-generated)
    email           TEXT    UNIQUE NOT NULL,
    display_name    TEXT,
    password_hash   TEXT,
    avatar_url      TEXT,
    role            TEXT    NOT NULL DEFAULT 'student'
                            CHECK (role IN ('student', 'instructor', 'admin')),
    is_active       INTEGER NOT NULL DEFAULT 1,        -- 0 | 1
    settings_json   TEXT    NOT NULL DEFAULT '{}',     -- JSON string
    created_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    last_seen_at    TEXT
);

CREATE INDEX IF NOT EXISTS idx_users_email  ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_role   ON users (role);

CREATE TRIGGER IF NOT EXISTS trg_users_updated_at
AFTER UPDATE ON users
BEGIN
  UPDATE users SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
END;


-- =============================================================
-- 2. COURSES
-- =============================================================

CREATE TABLE IF NOT EXISTS courses (
    id              TEXT    PRIMARY KEY,
    slug            TEXT    UNIQUE NOT NULL,
    exam_code       TEXT,
    title           TEXT    NOT NULL,
    description     TEXT,
    vendor          TEXT,
    version         TEXT,
    chapter_count   INTEGER NOT NULL DEFAULT 0,
    passing_score   REAL    NOT NULL DEFAULT 70.0,
    is_active       INTEGER NOT NULL DEFAULT 1,
    created_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX IF NOT EXISTS idx_courses_slug ON courses (slug);

CREATE TRIGGER IF NOT EXISTS trg_courses_updated_at
AFTER UPDATE ON courses
BEGIN
  UPDATE courses SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
END;


-- =============================================================
-- 3. MODULES
-- =============================================================

CREATE TABLE IF NOT EXISTS modules (
    id                  TEXT    PRIMARY KEY,
    course_id           TEXT    NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    slug                TEXT    NOT NULL,
    title               TEXT    NOT NULL,
    sort_order          INTEGER NOT NULL DEFAULT 0,
    topic_count         INTEGER NOT NULL DEFAULT 0,
    flashcard_count     INTEGER NOT NULL DEFAULT 0,
    quiz_question_count INTEGER NOT NULL DEFAULT 0,
    is_active           INTEGER NOT NULL DEFAULT 1,
    created_at          TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),

    UNIQUE (course_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_modules_course ON modules (course_id, sort_order);


-- =============================================================
-- 4. COURSE_ENROLLMENTS
-- =============================================================

CREATE TABLE IF NOT EXISTS course_enrollments (
    id          TEXT    PRIMARY KEY,
    user_id     TEXT    NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
    course_id   TEXT    NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    enrolled_by TEXT    REFERENCES users(id) ON DELETE SET NULL,
    enrolled_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    expires_at  TEXT,
    is_active   INTEGER NOT NULL DEFAULT 1,

    UNIQUE (user_id, course_id)
);

CREATE INDEX IF NOT EXISTS idx_enrollments_user   ON course_enrollments (user_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_course ON course_enrollments (course_id);


-- =============================================================
-- 5. LABS
-- =============================================================

CREATE TABLE IF NOT EXISTS labs (
    id          TEXT    PRIMARY KEY,
    module_id   TEXT    NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
    activity_id TEXT    UNIQUE NOT NULL,
    title       TEXT    NOT NULL,
    lab_type    TEXT    NOT NULL
                        CHECK (lab_type IN
                          ('click-order','click-match','fill-blank','code-lab')),
    instructions TEXT,
    max_score   INTEGER NOT NULL DEFAULT 100,
    passing_score INTEGER NOT NULL DEFAULT 70,
    time_limit_s INTEGER,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    is_active   INTEGER NOT NULL DEFAULT 1,
    created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX IF NOT EXISTS idx_labs_module ON labs (module_id, sort_order);


-- =============================================================
-- 6. USER_LAB_ENTITLEMENTS
-- =============================================================

CREATE TABLE IF NOT EXISTS user_lab_entitlements (
    id          TEXT    PRIMARY KEY,
    user_id     TEXT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lab_id      TEXT    NOT NULL REFERENCES labs(id)  ON DELETE CASCADE,
    granted_by  TEXT    REFERENCES users(id) ON DELETE SET NULL,
    granted_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    expires_at  TEXT,
    max_attempts INTEGER,

    UNIQUE (user_id, lab_id)
);

CREATE INDEX IF NOT EXISTS idx_entitlements_user ON user_lab_entitlements (user_id);
CREATE INDEX IF NOT EXISTS idx_entitlements_lab  ON user_lab_entitlements (lab_id);


-- =============================================================
-- 7. LAB_ATTEMPTS
-- =============================================================

CREATE TABLE IF NOT EXISTS lab_attempts (
    id              TEXT    PRIMARY KEY,
    user_id         TEXT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lab_id          TEXT    NOT NULL REFERENCES labs(id)  ON DELETE CASCADE,
    attempt_number  INTEGER NOT NULL DEFAULT 1,
    status          TEXT    NOT NULL DEFAULT 'in_progress'
                            CHECK (status IN
                              ('in_progress','submitted','abandoned','timed_out')),
    score           REAL,
    passed          INTEGER,                             -- 0 | 1 | NULL
    time_spent_s    INTEGER,
    answer_json     TEXT,                                -- JSON string
    feedback_json   TEXT,                                -- JSON string
    started_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    submitted_at    TEXT,
    created_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX IF NOT EXISTS idx_lab_attempts_user   ON lab_attempts (user_id);
CREATE INDEX IF NOT EXISTS idx_lab_attempts_lab    ON lab_attempts (lab_id);
CREATE INDEX IF NOT EXISTS idx_lab_attempts_status ON lab_attempts (status);


-- =============================================================
-- 8. LAB_EVENT_LOG
-- =============================================================

CREATE TABLE IF NOT EXISTS lab_event_log (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    attempt_id  TEXT    NOT NULL REFERENCES lab_attempts(id) ON DELETE CASCADE,
    user_id     TEXT    NOT NULL REFERENCES users(id)        ON DELETE CASCADE,
    lab_id      TEXT    NOT NULL REFERENCES labs(id)         ON DELETE CASCADE,
    event_type  TEXT    NOT NULL,
    payload_json TEXT,
    created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX IF NOT EXISTS idx_events_attempt ON lab_event_log (attempt_id, created_at);
CREATE INDEX IF NOT EXISTS idx_events_user    ON lab_event_log (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_events_type    ON lab_event_log (event_type);


-- =============================================================
-- 9. MODULE_PROGRESS
--    topics_seen stored as JSON array string: '[0,1,3]'
-- =============================================================

CREATE TABLE IF NOT EXISTS module_progress (
    id              TEXT    PRIMARY KEY,
    user_id         TEXT    NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
    module_id       TEXT    NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
    course_id       TEXT    NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    active_tab      INTEGER NOT NULL DEFAULT 0,
    topics_seen     TEXT    NOT NULL DEFAULT '[]',           -- JSON int array
    topic_current   INTEGER NOT NULL DEFAULT 0,
    flashcard_index INTEGER NOT NULL DEFAULT 0,
    quiz_index      INTEGER NOT NULL DEFAULT 0,
    quiz_score      REAL,
    quiz_correct    INTEGER NOT NULL DEFAULT 0,
    quiz_attempted  INTEGER NOT NULL DEFAULT 0,
    progress_pct    INTEGER NOT NULL DEFAULT 0
                            CHECK (progress_pct BETWEEN 0 AND 100),
    notes_text      TEXT,
    is_complete     INTEGER NOT NULL DEFAULT 0,              -- 0 | 1
    completed_at    TEXT,
    last_active_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),

    UNIQUE (user_id, module_id)
);

CREATE INDEX IF NOT EXISTS idx_progress_user    ON module_progress (user_id);
CREATE INDEX IF NOT EXISTS idx_progress_course  ON module_progress (user_id, course_id);

CREATE TRIGGER IF NOT EXISTS trg_progress_updated_at
AFTER UPDATE ON module_progress
BEGIN
  UPDATE module_progress
  SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
  WHERE id = NEW.id;
END;


-- =============================================================
-- 10. QUIZ_ATTEMPTS
--     topics_filter stored as JSON array string: '["Domain 1","Domain 3"]'
-- =============================================================

CREATE TABLE IF NOT EXISTS quiz_attempts (
    id              TEXT    PRIMARY KEY,
    user_id         TEXT    NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
    course_id       TEXT    NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    module_id       TEXT    REFERENCES modules(id) ON DELETE CASCADE,
    quiz_type       TEXT    NOT NULL
                            CHECK (quiz_type IN ('chapter','practice','acronym')),
    mode            TEXT    NOT NULL DEFAULT 'training'
                            CHECK (mode IN ('training','exam')),
    question_count  INTEGER NOT NULL,
    correct_count   INTEGER NOT NULL DEFAULT 0,
    score           REAL,
    topics_filter   TEXT,                                    -- JSON array string
    answer_json     TEXT,                                    -- JSON array string
    started_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    completed_at    TEXT,
    created_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX IF NOT EXISTS idx_quiz_attempts_user   ON quiz_attempts (user_id);
CREATE INDEX IF NOT EXISTS idx_quiz_attempts_module ON quiz_attempts (module_id);
CREATE INDEX IF NOT EXISTS idx_quiz_attempts_type   ON quiz_attempts (user_id, quiz_type);


-- =============================================================
-- 11. COMPLETION_CERTIFICATES
-- =============================================================

CREATE TABLE IF NOT EXISTS completion_certificates (
    id                  TEXT    PRIMARY KEY,
    user_id             TEXT    NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
    course_id           TEXT    NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    certificate_number  TEXT    UNIQUE NOT NULL,
    overall_score       REAL,
    modules_completed   INTEGER NOT NULL,
    total_modules       INTEGER NOT NULL,
    total_time_s        INTEGER,
    pdf_url             TEXT,
    issued_at           TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    is_valid            INTEGER NOT NULL DEFAULT 1,
    revoked_at          TEXT,
    revoked_reason      TEXT
);

CREATE INDEX IF NOT EXISTS idx_certs_user   ON completion_certificates (user_id);
CREATE INDEX IF NOT EXISTS idx_certs_course ON completion_certificates (course_id);


-- =============================================================
-- REPORTING VIEWS (SQLite-compatible)
-- =============================================================

CREATE VIEW IF NOT EXISTS vw_user_course_summary AS
SELECT
    e.user_id,
    e.course_id,
    c.slug                                          AS course_slug,
    c.title                                         AS course_title,
    COUNT(m.id)                                     AS total_modules,
    SUM(CASE WHEN mp.is_complete = 1 THEN 1 ELSE 0 END) AS modules_complete,
    ROUND(AVG(COALESCE(mp.progress_pct, 0)), 1)    AS avg_progress_pct,
    ROUND(AVG(mp.quiz_score), 1)                   AS avg_quiz_score,
    MAX(mp.last_active_at)                          AS last_active_at,
    EXISTS (
      SELECT 1 FROM completion_certificates cc
      WHERE cc.user_id = e.user_id
        AND cc.course_id = e.course_id
        AND cc.is_valid = 1
    )                                               AS has_certificate
FROM course_enrollments e
JOIN courses c                  ON c.id = e.course_id
JOIN modules m                  ON m.course_id = e.course_id AND m.is_active = 1
LEFT JOIN module_progress mp    ON mp.user_id = e.user_id AND mp.module_id = m.id
WHERE e.is_active = 1
GROUP BY e.user_id, e.course_id, c.slug, c.title;


CREATE VIEW IF NOT EXISTS vw_lab_performance AS
SELECT
    l.activity_id,
    l.title                                                    AS lab_title,
    l.lab_type,
    m.slug                                                     AS module_slug,
    c.slug                                                     AS course_slug,
    COUNT(la.id)                                               AS total_attempts,
    SUM(CASE WHEN la.status='submitted' THEN 1 ELSE 0 END)    AS submitted_attempts,
    SUM(CASE WHEN la.passed=1 THEN 1 ELSE 0 END)              AS passed_attempts,
    ROUND(AVG(CASE WHEN la.status='submitted' THEN la.score END), 1) AS avg_score,
    COUNT(DISTINCT la.user_id)                                 AS unique_users
FROM labs l
JOIN modules m          ON m.id = l.module_id
JOIN courses c          ON c.id = m.course_id
LEFT JOIN lab_attempts la ON la.lab_id = l.id
GROUP BY l.id, l.activity_id, l.title, l.lab_type, m.slug, c.slug;
